# Defalut applications
export EDITOR="nvim"
export TERMINAL="alacritty"

# Homebrew path
export PATH=/opt/homebrew/bin:$PATH

# NVM path
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# Android sdk
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$ANDROID_HOME/build-tools/31.0.0/

# Asprite
export PATH=$PATH:$HOME/aseprite/build/bin

# Java home
export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home

# Flutter
export PATH="$PATH:$HOME/flutter/bin"

# Pywal
export PATH=$PATH:/opt/homebrew/lib/python3.11/site-packages

#Start tmux
[ -z "$TMUX"  ] && { exec tmux new-session && exit;}
