# Oh-my-zsh path
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="robbyrussell"
PROMPT='%c %F{cyan}% ⩥ %f'

# Plugins
plugins=(git)

# Oh-my-zsh
source $ZSH/oh-my-zsh.sh

# profile
source $HOME/.config/zsh/zprofile

# Aliases
source $HOME/.config/zsh/alias

# Envs
source $HOME/.config/zsh/envs
