# Oh-my-zsh path
export ZSH="$HOME/.oh-my-zsh"

# Plugins
plugins=(git)

# Oh-my-zsh
source $ZSH/oh-my-zsh.sh

# profile
source $HOME/.config/zsh/zprofile

# Aliases
source $HOME/.config/zsh/alias

# Envs
source $HOME/.config/zsh/envs
